## Introduction to Data Structures

A data structure is a format for organizing, processing, retrieving, and storing data. Efficient data structures are key to designing efficient algorithms. Different types of data structures are suited to different kinds of applications, and some are highly specialized to specific tasks.



## Introduction to Array

An array is a data structure that holds a fixed number of elements of the same data type. Arrays are used to store collections of data in a structured way, and they allow for efficient access and manipulation of these elements.

Arrays are a collection of elements/values, that can have one or more dimensions. An array of one dimension is called a Vector while having two dimensions is called a Matrix.


#### Key Characteristics of Arrays

- **Fixed Size:** The size of the array is defined at the time of creation and cannot be changed.
- **Homogeneous Elements:** All elements in an array are of the same data type.
- **Indexed Access:** Elements can be accessed using an index, with the first element at index 0

In [1]:
array = []  # list in pythonic ways

array1 = [1,2,3,4,5]

type(array1)

list

**Example 1: Creating and Accessing a List**

In [2]:
# Creating a list of integers
l1 = [10, 20, 30, 40, 50]

# Accessing elements of the list using indices
first_element = l1[0]  # Accessing the first element
second_element = l1[1]  # Accessing the second element

# Modifying an element in the list
l1[4] =100 # Changing the third element to 35

# Printing the list and accessed elements
print("List:", l1)
print("First Element:", first_element)
print("Second Element:", second_element)
print("Modified List:", l1)

List: [10, 20, 30, 40, 100]
First Element: 10
Second Element: 20
Modified List: [10, 20, 30, 40, 100]


In [2]:
type(array)

list

**Using the array Module**
- Python also has a built-in array module that provides a more array-like data structure with type constraints.

**Example 2: Creating and Accessing an Array Using array Module**

In [4]:
import array as arr

# Creating an array of integers
array = arr.array('i', [10, 20, 30, 40, 50])

# Accessing elements of the array using indices
first_element = array[0]  # Accessing the first element
second_element = array[1]  # Accessing the second element

# Modifying an element in the array
array[2] = 35  # Changing the third element to 35

# Printing the array and accessed elements
print("Array:", array)
print("First Element:", first_element)
print("Second Element:", second_element)
print("Modified Array:", array)

Array: array('i', [10, 20, 35, 40, 50])
First Element: 10
Second Element: 20
Modified Array: array('i', [10, 20, 35, 40, 50])


In [4]:
import array as arr

# Creating an array of integers
array = arr.array([10, 20, 30, 40, 50])

# Accessing elements of the array using indices
first_element = array[0]  # Accessing the first element
second_element = array[1]  # Accessing the second element

# Modifying an element in the array
array[2] = 35  # Changing the third element to 35

# Printing the array and accessed elements
print("Array:", array)
print("First Element:", first_element)
print("Second Element:", second_element)
print("Modified Array:", array)

TypeError: array() argument 1 must be a unicode character, not list

In [3]:
import array as arr

# Creating an array of integers
array = arr.array('i', [10, 20, 30, 40, 50])

type(array)

array.array

In [5]:
type(array)

array.array

In [6]:
import array as arr

# Creating an array of integers
array = arr.array([10, 20, 30, 40, 50]) ############ Removed i

# Accessing elements of the array using indices
first_element = array[0]  # Accessing the first element
second_element = array[1]  # Accessing the second element

# Modifying an element in the array
array[2] = 35  # Changing the third element to 35

# Printing the array and accessed elements
print("Array:", array)
print("First Element:", first_element)
print("Second Element:", second_element)
print("Modified Array:", array)


TypeError: array() argument 1 must be a unicode character, not list

**Example 3:**

##### 'b': unsigned char

**Range: -128 to 127.**

In [5]:
import array as arr
char_array = arr.array('b', [65, 66, 67])
print(char_array)  # Output: array('b', [65, 66, 67])

array('b', [65, 66, 67])


**Let's Increase the values**

In [6]:
import array as arr
char_array = arr.array('b', [200, 180, 300])
print(char_array)  # Output: array('b', [65, 66, 67])

OverflowError: signed char is greater than maximum

**Here are some of the most commonly used type codes:**

'b': signed char -> Range From -128 to 127.

'B': unsigned char -> Range From: From 0 to 255

'u': Unicode character

'h': signed short

'H': unsigned short

'i': signed int

'I': unsigned int

'l': signed long

'L': unsigned long

'q': signed long long

'Q': unsigned long long

'f': float

'd': double

In [ ]:
import array as arr # Module
pinstall numpy # Library

### What is NumPy?

NumPy, short for Numerical Python, is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures efficiently.

**Why Use NumPy?**

- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

**Using Python List**

In [11]:
import time

# Create two large lists of 10 million elements each
list1 = list(range(10000000))
list2 = list(range(10000000))

# Measure the time taken for element-wise addition using lists
start_time = time.time()

result_list = [x + y for x, y in zip(list1, list2)]

end_time = time.time()

print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

Time taken using Python lists: 3.613326 seconds


**Using NumPy Array**

In [12]:
import numpy as np
import array as arr
import time

# Create two large NumPy arrays of 10 million elements each
array1 = np.arange(10000000)
array2 = np.arange(10000000)

# Measure the time taken for element-wise addition using NumPy arrays
start_time = time.time()

result_array = array1 + array2

end_time = time.time()

print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time - start_time))

Time taken using NumPy arrays: 0.045555 seconds


**Why is NumPy Faster Than Lists?**

- **Contiguous Memory:** NumPy arrays use a single block of memory, making data access quicker compared to Python lists, which store pointers to scattered memory locations.

- **Same Data Type:** NumPy arrays hold elements of the same type for optimization and faster computations. Python lists can store mixed types, adding extra overhead.

- **Optimized Code:** NumPy is implemented in low-level languages like C, which are much faster than the high-level Python code used for lists.

- **Vectorized Operations:** NumPy supports performing operations on entire arrays at once, while Python lists require slower, manual element-by-element processing.

# NumPy Implementation

In [13]:
!pip install numpy

In [8]:
import numpy as np # np loads the NumPy library and gives it a shorter name, np, for easier use in your code.

In [11]:
list1 = []

arr = np.array(list1)

print(type(list1))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
arr1 = np.array([])

type(arr1)

numpy.ndarray

In [20]:
import numpy as np

# Create an empty Python list
py_list = []

# Convert to an empty list to Empty NumPy array
empty_np_array = np.array(py_list)

print(type(py_list))
print("Converted NumPy Array:", empty_np_array)
print(type(empty_np_array))

<class 'list'>
Converted NumPy Array: []
<class 'numpy.ndarray'>


In [15]:
# Creating array using NumPy
import numpy as np

arr = np.array([1, 2, 3, 4, 5]) # 1D

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
# NumPy Array Indexing # alias
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [14]:
# check if a NumPy array is 1D or 2D

import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6],
                    [4, 5, 6]])

# Check if the arrays are 1D or 2D
print("Array 1D is 1D:", array_1d.ndim == 1)
print("Array 2D is 2D:", array_2d.ndim == 2)


Array 1D is 1D: True
Array 2D is 2D: True


In [17]:
array_1d = np.array([[[[[1, 2, 3], [4, 5, 6], [7,8,9]]]]])
array_1d.ndim

5

In [ ]:
array_3d = np.array([[[1, 2, 3], 
                      [4, 5, 6], 
                      [7,8,9]]])


array_4d = np.array([[[[1, 2, 3], 
                       [4, 5, 6], 
                       [7,8,9]]]])


In [28]:
import numpy as np

# Creating arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7,8,9]]])
array_4d = np.array([[[[1, 2, 3], [4, 5, 6], [7,8,9]]]])
# Check dimensions
def check_array_dim(arr):
    return arr.ndim

print("Array 1D has", check_array_dim(array_1d), "dimension(s)")
print("Array 2D has", check_array_dim(array_2d), "dimension(s)")
print("Array 3D has", check_array_dim(array_3d), "dimension(s)")
print("Array 4D has", check_array_dim(array_4d), "dimension(s)")

Array 1D has 1 dimension(s)
Array 2D has 2 dimension(s)
Array 3D has 3 dimension(s)
Array 4D has 4 dimension(s)


**Access 2-D Arrays**
- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [30]:
import numpy as np

arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])

print("5th element on 2nd dim:", arr[1, 4])

5th element on 2nd dim: 10


**NumPy Array Slicing**
- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step].

- If we don’t pass start its considered 0

- If we don’t pass end its considered length of array in that dimension

- If we don’t pass step its considered 1.

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


**Negative Slicing**
- Use the minus operator to refer to an index from the end:

In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


**NumPy Array Shape**
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.



In [33]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


**NumPy Array Reshaping** 

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # Convert the following 1-D array with 12 elements into a 2-D array.

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Reshape From 1-D to 3-D**

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### Array Operations
Let's look at a breif overview of various operations that can be performed on an array, such as **traversal, searching, insertion, deletion, and sorting.**

- NumPy Array Traversal:


In [37]:
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Traversing the array
for element in array:
    print(element)

10
20
30
40
50


- Python List Traversal:

In [38]:
# Creating a list
list_ = [10, 20, 30, 40, 50]

# Traversing the list
for element in list_:
    print(element)

10
20
30
40
50


#### 2. Searching
- Searching involves finding specific elements within the array.

**NumPy Array Search:**

In [40]:
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Searching for an element
index = np.where(array == 30)
print("Index of 30:", index[0][0])

Index of 30: 2


In [42]:
my_array = np.array([1, 2, 3, 4, 5])
search_element = 3

for index, element in enumerate(my_array):
    if element == search_element:
        print("Element found at index:", index)
        break
else:
    print("Element not found in the array.")

Element found at index: 2


- Python List Search:

In [41]:
# Creating a list
list_ = [10, 20, 30, 40, 50]

# Searching for an element
index = list_.index(30)
print("Index of 30:", index)

Index of 30: 2


#### 3. Insertion
Insertion involves adding elements to the array.

- NumPy Array Insertion:

In [43]:
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40])

# Inserting an element
new_array = np.insert(array, 2, 25)
print("Array after insertion:", new_array)

Array after insertion: [10 20 25 30 40]


- Python List Insertion:

In [44]:
# Creating a list
list_ = [10, 20, 30, 40]

# Inserting an element
list_.insert(2, 25)
print("List after insertion:", list_)

List after insertion: [10, 20, 25, 30, 40]


#### 4. Deletion
Deletion involves removing elements from the array.

- NumPy Array Deletion:

In [45]:
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40])

# Deleting an element
new_array = np.delete(array, 2)
print("Array after deletion:", new_array)

Array after deletion: [10 20 40]


In [47]:
import numpy as np

# Suppose you have an existing numpy array
my_array = np.array([1, 2, 3, 4, 5])

# Index of the element you want to delete
index_to_delete = 2

# Delete the element at the specified index
new_array = np.delete(my_array, index_to_delete)

print(new_array)

[1 2 4 5]


- Python List Deletion:

In [46]:
# Creating a list
list_ = [10, 20, 30, 40]

# Deleting an element
del list_[2]
print("List after deletion:", list_)

List after deletion: [10, 20, 40]


#### 5. Sorting
Sorting involves arranging the elements in a specific order.

- NumPy Array Sorting:

In [48]:
import numpy as np

# Creating an array
array = np.array([40, 10, 30, 20])

# Sorting the array
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

Sorted array: [10 20 30 40]


- Python List Sorting:


In [49]:
# Creating a list
list_ = [40, 10, 30, 20]

# Sorting the list
list_.sort()
print("Sorted list:", list_)

Sorted list: [10, 20, 30, 40]


## 🔍 Activity: Fill in the Blanks
**Consider the following NumPy array: my_array = np.array([10, 20, 30, 40, 50])**

- The number of elements in the array is ________.

- To access the third element of the array, you would use the index ________.

- To add a new element with the value 60 at the end of the array, you would use the method ________.

- To update the value of the second element to 25, you would use the assignment statement ________.

- To remove the element with the value 40 from the array, you would use the method ________.

- The method used to find the index of a specific element in the array is ________.

- The process of extracting a portion of the array is known as ________.

- To slice the array from index 1 to index 3 (exclusive), you would use the syntax ________.

- To check if the value 30 is present in the array, you would use the expression ________.

- To reverse the order of elements in the array, you would use the method ________.

In [51]:
import numpy as np

# Consider the following NumPy array:
my_array = np.array([10, 20, 30, 40, 50])

# 1. The number of elements in the array is:
num_elements = my_array.size
print("Number of elements:", num_elements)

# 2. To access the third element of the array, you would use the index:
third_element_index = 2
third_element = my_array[third_element_index]
print("Third element:", third_element)

# 3. To add a new element with the value 60 at the end of the array, you would use the method:
my_array = np.append(my_array, 60)
print("Array after appending 60:", my_array)

# 4. To update the value of the second element to 25, you would use the assignment statement:
my_array[1] = 25
print("Array after updating second element:", my_array)

# 5. To remove the element with the value 40 from the array, you would use the method:
my_array = my_array[my_array != 40]
print("Array after removing 40:", my_array)

# 6. The method used to find the index of a specific element in the array is:
index_of_element = np.where(my_array == 30)[0][0]
print("Index of 30:", index_of_element)

# 7. The process of extracting a portion of the array is known as:
# (No code needed here; just a comment)
# slicing

# 8. To slice the array from index 1 to index 3 (exclusive), you would use the syntax:
sliced_array = my_array[1:3]
print("Sliced array (index 1 to 3 exclusive):", sliced_array)

# 9. To check if the value 30 is present in the array, you would use the expression:
is_30_present = 30 in my_array
print("Is 30 present in the array?", is_30_present)

# 10. To reverse the order of elements in the array, you would use the method:
my_array = np.flip(my_array)
print("Array after reversing:", my_array)


Number of elements: 5
Third element: 30
Array after appending 60: [10 20 30 40 50 60]
Array after updating second element: [10 25 30 40 50 60]
Array after removing 40: [10 25 30 50 60]
Index of 30: 2
Sliced array (index 1 to 3 exclusive): [25 30]
Is 30 present in the array? True
Array after reversing: [60 50 30 25 10]
